//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.1008
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CS.Resource {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class en_us {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal en_us() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CS.Resource.en-us", typeof(en_us).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 abc 的本地化字符串。
        /// </summary>
        public static string a {
            get {
                return ResourceManager.GetString("a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 About Page 的本地化字符串。
        /// </summary>
        public static string About_Page {
            get {
                return ResourceManager.GetString("About Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 About Us 的本地化字符串。
        /// </summary>
        public static string About_Us {
            get {
                return ResourceManager.GetString("About Us", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Click Me 的本地化字符串。
        /// </summary>
        public static string clickme {
            get {
                return ResourceManager.GetString("clickme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Copyright 的本地化字符串。
        /// </summary>
        public static string Copyright {
            get {
                return ResourceManager.GetString("Copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete Failed! 的本地化字符串。
        /// </summary>
        public static string deletefailed {
            get {
                return ResourceManager.GetString("deletefailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Home 的本地化字符串。
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Home Page 的本地化字符串。
        /// </summary>
        public static string Home_Page {
            get {
                return ResourceManager.GetString("Home Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Change Language 的本地化字符串。
        /// </summary>
        public static string lang {
            get {
                return ResourceManager.GetString("lang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Js alert msg! 的本地化字符串。
        /// </summary>
        public static string msg {
            get {
                return ResourceManager.GetString("msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please Input CustomerName! 的本地化字符串。
        /// </summary>
        public static string str_InputCustomerName {
            get {
                return ResourceManager.GetString("str_InputCustomerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 My Sample MVC Application 的本地化字符串。
        /// </summary>
        public static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 To learn more about ASP.NET MVC visit 的本地化字符串。
        /// </summary>
        public static string String2 {
            get {
                return ResourceManager.GetString("String2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Test 的本地化字符串。
        /// </summary>
        public static string Test {
            get {
                return ResourceManager.GetString("Test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Welcome to ASP.NET MVC! 的本地化字符串。
        /// </summary>
        public static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
    }
}
